version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: kimenyi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clickbar
    volumes:
      - ./data:/var/lib/postgresql/data
